# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-Type
version:      0.01.15
version_from: Type.pm
installdirs:  site
requires:
    Attribute::Abstract:           0.01
    Business::CINS:                1.13
    Business::CreditCard:          0.27
    Business::ISSN:                0.90
    Business::UPC:                 0.04
    Class::Maker:                  0.05.17
    Class::Multimethods:           1.70
    Data::Iter:                    0
    Date::Parse:                   2.27
    DBI:                           1.30
    Email::Valid:                  0.14
    Error:                         0.15
    HTML::Lint:                    1.23
    IO::Extended:                  0.05
    Locale::Language:              2.02
    Locale::SubCountry:            
    Net::IPv6Addr:                 0.2
    Pod::Find:                     0.23
    Regexp::Common:                2.113
    String::ExpandEscapes:         0.01
    Text::TabularDisplay:          1.18
    Tie::ListKeyedHash:            0.41
    X500::DN:                      0.28
    XML::Parser:                   2.31
    XML::Schema:                   0.07

distribution_type: module
generated_by: ExtUtils::MakeMaker version 1.23
